name: Daily Stock Data Update

on:
  schedule:
    - cron: "0 13 * * *"
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: "디버그 로그 활성화"
        required: false
        default: false
        type: boolean

jobs:
  update-stock-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install Dependencies
        run: npm install
        
      - name: Run Stock Updates
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_KEY }}
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        run: |
          npx ts-node scripts/update.ts